# Generated by Django 5.2.7 on 2025-11-13 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_post_comments_count_comment_post_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='reated_at',
            new_name='created_at',
        ),
    ]
