# Generated by Django 5.2.7 on 2025-11-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_reated_at_comment_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
