# Generated by Django 5.2.7 on 2025-11-14 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_trend'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trend',
            old_name='hastag',
            new_name='hashtag',
        ),
    ]
