# Generated by Django 5.2.7 on 2025-11-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_rename_hastag_trend_hashtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
