# Generated by Django 5.2.7 on 2025-11-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type_of_notification',
            field=models.CharField(choices=[('new_friendrequest', 'New Friend Request'), ('accepted_friendrequest', 'Accepted Friend Request'), ('rejected_friendrequest', 'Rejected Friend Request'), ('post_like', 'Post Like'), ('post_comment', 'Post Comment')], max_length=50),
        ),
    ]
